export const USER_ROLES = {
  USER: "USER",
  ADMIN: "ADMIN",
};

export const ACCOUNT_TYPES = {
  TEACHER: "TEACHER",
  TEACHER_LEARNER: "TEACHER_LEARNER",
  LEARNER: "LEARNER",
};

export const TEACHING_STYLES = {
  STEP_BY_STEP: "STEP_BY_STEP",
  HANDS_ON: "HANDS_ON",
  CONCEPT_FOCUSED: "CONCEPT_FOCUSED",
  PROJECT_BASED: "PROJECT_BASED",
  INTERACTIVE: "INTERACTIVE",
  VISUAL: "VISUAL",
  NOT_SURE: "NOT_SURE",
};

export const LANGUAGES = {
  ENGLISH: "ENGLISH",
  HINDI: "HINDI",
  BENGALI: "BENGALI",
  TELUGU: "TELUGU",
  MARATHI: "MARATHI",
  TAMIL: "TAMIL",
  GUJARATI: "GUJARATI",
  KANNADA: "KANNADA",
  MALAYALAM: "MALAYALAM",
  PUNJABI: "PUNJABI",
};

export const SKILL_CATEGORIES = {
  TECHNOLOGY_PROGRAMMING: "TECHNOLOGY_PROGRAMMING",
  DESIGN_CREATIVE: "DESIGN_CREATIVE",
  BUSINESS_ENTREPRENEURSHIP: "BUSINESS_ENTREPRENEURSHIP",
  MARKETING_SALES: "MARKETING_SALES",
  FINANCE_ACCOUNTING: "FINANCE_ACCOUNTING",
  LANGUAGES: "LANGUAGES",
  ACADEMIC_TUTORING: "ACADEMIC_TUTORING",
  SCIENCE_ENGINEERING: "SCIENCE_ENGINEERING",
  WRITING_COMMUNICATION: "WRITING_COMMUNICATION",
  MUSIC_AUDIO: "MUSIC_AUDIO",
  PHOTOGRAPHY_VIDEO: "PHOTOGRAPHY_VIDEO",
  ART_CRAFTS: "ART_CRAFTS",
  DANCE_PERFORMING_ARTS: "DANCE_PERFORMING_ARTS",
  HEALTH_FITNESS: "HEALTH_FITNESS",
  SPORTS: "SPORTS",
  COOKING_FOOD: "COOKING_FOOD",
  CAREER_PROFESSIONAL: "CAREER_PROFESSIONAL",
  PERSONAL_DEVELOPMENT: "PERSONAL_DEVELOPMENT",
  TRADES_DIY: "TRADES_DIY",
  FASHION_BEAUTY: "FASHION_BEAUTY",
  GAMING_ESPORTS: "GAMING_ESPORTS",
  DATA_ANALYTICS: "DATA_ANALYTICS",
  LAW_LEGAL: "LAW_LEGAL",
  OTHER: "OTHER",
};
