export const ERROR_CODES = {
  // General
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  INVALID_REQUEST: "INVALID_REQUEST",

  // Validation
  MISSING_REQUIRED_FIELDS: "MISSING_REQUIRED_FIELDS",
  INVALID_FIELD_VALUE: "INVALID_FIELD_VALUE",
  INVALID_ACCOUNT_TYPE: "INVALID_ACCOUNT_TYPE",
  INVALID_TEACHING_STYLE: "INVALID_TEACHING_STYLE",
  INVALID_LANGUAGE: "INVALID_LANGUAGE",

  // Authentication
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",
  INVALID_ACCESS_TOKEN: "INVALID_ACCESS_TOKEN",
  ACCESS_TOKEN_EXPIRED: "ACCESS_TOKEN_EXPIRED",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",

  // Authorization
  FORBIDDEN: "FORBIDDEN",
  INSUFFICIENT_ROLE: "INSUFFICIENT_ROLE",
  ACCOUNT_TYPE_NOT_PERMITTED: "ACCOUNT_TYPE_NOT_PERMITTED",

  // User / Account
  USER_NOT_FOUND: "USER_NOT_FOUND",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  USERNAME_ALREADY_EXISTS: "USERNAME_ALREADY_EXISTS",
  INVALID_ACCOUNT_UPGRADE: "INVALID_ACCOUNT_UPGRADE",
  TEACHING_PROFILE_INCOMPLETE: "TEACHING_PROFILE_INCOMPLETE",
};
